#!/usr/bin/env ruby

key = ARGV[0]

stations = \
    { "1" => "http://lr1mp1.latvijasradio.lv:8012/listen.pls" \
    , "2" => "http://lr1mp1.latvijasradio.lv:8002/listen.pls" \
    , "3" => "http://lr1mp1.latvijasradio.lv:8004/listen.pls" \
    , "4" => "http://lr1mp1.latvijasradio.lv:8020/listen.pls" \
    , "5" => "http://live.pieci.lv/live19-hq.mp3" \
    , "naba" => "http://muste.radio.org.lv:1935/shoutcast/naba.stream/playlist.m3u8" \
    , "lkr" => "http://91.203.71.10:8006/;?type=http&nocache=905" \
    }

unless (link = stations[key])
    puts "usage: #{ $0 } <station>"
    puts stations.to_a.map(&:inspect)
    exit
end

exec 'mpv', link
